services:
  postgres_db:
    container_name: postgres-db
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: